-- dosyası: supabase/migrations/003_add_supplier_assignment_and_user_details.sql (BASİTLEŞTİRİLMİŞ - UUID'siz ve RLS'siz)

-- 1. Kullanıcılar tablosuna telefon ve adres sütunlarını ekle (varsa hata verme)
ALTER TABLE public.kullanicilar
ADD COLUMN IF NOT EXISTS telefon_no TEXT NULL,
ADD COLUMN IF NOT EXISTS adres TEXT NULL;

-- 2. Toplayıcı-Tedarikçi atama tablosunu oluştur
CREATE TABLE IF NOT EXISTS public.toplayici_tedarikci_atananlari (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- ON DELETE CASCADE: Eğer bir kullanıcı veya tedarikçi silinirse,
    -- ilgili atama kayıtları da otomatik olarak silinsin.
    toplayici_id BIGINT NOT NULL REFERENCES public.kullanicilar(id) ON DELETE CASCADE,
    tedarikci_id BIGINT NOT NULL REFERENCES public.tedarikciler(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,

    -- Bir toplayıcıya aynı tedarikçinin birden fazla kez atanmasını engelle
    CONSTRAINT unique_toplayici_tedarikci UNIQUE (toplayici_id, tedarikci_id)
);

-- 3. Yeni tabloya erişimi kolaylaştırmak için index ekle
-- Bu indexler, belirli bir toplayıcıya veya tedarikçiye ait atamaları hızlıca bulmamızı sağlar.
CREATE INDEX IF NOT EXISTS idx_toplayici_atananlari ON public.toplayici_tedarikci_atananlari (toplayici_id);
CREATE INDEX IF NOT EXISTS idx_tedarikci_atananlari ON public.toplayici_tedarikci_atananlari (tedarikci_id);

-- ÖNEMLİ: Bu versiyonda RLS politikaları veya get_my_user_id() fonksiyonu YOKTUR.
-- Filtreleme backend kodunda yapılacaktır.