-- dosyası: supabase/migrations/005_create_price_tariff.sql
-- Süt fiyat tarifelerini yönetmek için yeni bir tablo oluşturur.

CREATE TABLE IF NOT EXISTS public.sut_fiyat_tarifesi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    
    -- Hangi şirkete ait olduğu
    sirket_id INTEGER NOT NULL REFERENCES public.sirketler(id) ON DELETE CASCADE,
    
    -- Fiyatın hangi tarihten itibaren geçerli olacağı
    baslangic_tarihi DATE NOT NULL,
    
    -- Fiyatın hangi tarihe kadar geçerli olacağı (Bu tarih DAHİL)
    -- NULL ise, o tarihten sonra hep bu fiyat geçerli demektir.
    bitis_tarihi DATE NULL,
    
    -- O tarihteki litre fiyatı
    fiyat NUMERIC(10, 2) NOT NULL,
    
    -- Aynı şirket için çakışan tarih aralıkları olmamasını zorunlu kıl
    -- Şimdilik bu kısıtlamayı eklemeyelim, kod tarafında kontrol edebiliriz.
    
    -- Hızlı arama için index
    CONSTRAINT sut_fiyat_tarifesi_sirket_id_baslangic_tarihi_key UNIQUE (sirket_id, baslangic_tarihi)
);

-- Bu tabloya hızlıca erişmek için index oluşturalım
CREATE INDEX IF NOT EXISTS idx_sut_fiyat_tarifesi_sirket_tarih
ON public.sut_fiyat_tarifesi (sirket_id, baslangic_tarihi DESC);

-- NOT: RLS (Satır Seviyesi Güvenlik) politikaları kaldırıldı.
-- Güvenlik ve yetkilendirme, Flask/Python (decorators.py) katmanında yapılmaktadır.