-- dosyası: supabase/migrations/006_create_genel_masraflar.sql
-- Şirketlerin genel giderlerini (maaş, yakıt, kira vb.)
-- ve bu giderlerin kategorilerini yönetmek için iki yeni tablo oluşturur.

-- 1. Masraf Kategorileri Tablosu
CREATE TABLE IF NOT EXISTS public.masraf_kategorileri (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    
    -- Hangi şirkete ait olduğu
    sirket_id INTEGER NOT NULL REFERENCES public.sirketler(id) ON DELETE CASCADE,
    
    -- Kategori adı (örn: "Personel Maaşları", "Nakliye Giderleri", "Ofis Kirası")
    kategori_adi TEXT NOT NULL,
    
    -- Aynı şirket için aynı kategori adının tekrar etmesini engelle
    CONSTRAINT masraf_kategorileri_sirket_id_kategori_adi_key UNIQUE (sirket_id, kategori_adi)
);

-- 2. Genel Masraflar Tablosu
CREATE TABLE IF NOT EXISTS public.genel_masraflar (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    
    -- Hangi şirkete ait olduğu
    sirket_id INTEGER NOT NULL REFERENCES public.sirketler(id) ON DELETE CASCADE,
    
    -- Hangi kullanıcı (yetkili/muhasebeci) tarafından eklendiği
    kullanici_id BIGINT REFERENCES public.kullanicilar(id) ON DELETE SET NULL,
    
    -- Hangi masraf kategorisine ait olduğu
    -- Kategori silinirse, masraf kaydı silinmesin ama kategorisi NULL olsun (ON DELETE SET NULL)
    kategori_id BIGINT REFERENCES public.masraf_kategorileri(id) ON DELETE SET NULL,
    
    -- Masrafın tutarı
    tutar NUMERIC(10, 2) NOT NULL,
    
    -- Masrafın ne zaman yapıldığı (fatura tarihi vb.)
    masraf_tarihi DATE NOT NULL,
    
    -- Opsiyonel açıklama alanı
    aciklama TEXT
);

-- Hızlı arama için indexler
CREATE INDEX IF NOT EXISTS idx_genel_masraflar_sirket_id_tarih
ON public.genel_masraflar (sirket_id, masraf_tarihi DESC);

CREATE INDEX IF NOT EXISTS idx_genel_masraflar_kategori_id
ON public.genel_masraflar (kategori_id);

CREATE INDEX IF NOT EXISTS idx_masraf_kategorileri_sirket_id
ON public.masraf_kategorileri (sirket_id);