-- 1. Tankerleri tutacak ana tablo
CREATE TABLE public.tankerler (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    firma_id INTEGER NOT NULL REFERENCES public.sirketler(id) ON DELETE CASCADE,
    tanker_adi TEXT NOT NULL,
    kapasite_litre NUMERIC(10, 2) NOT NULL DEFAULT 0,
    mevcut_doluluk NUMERIC(10, 2) NOT NULL DEFAULT 0
);
-- İndeks
CREATE INDEX idx_tankerler_firma_id ON public.tankerler(firma_id);


-- 2. Toplayıcıları tankerlere atamak için bağlantı tablosu
CREATE TABLE public.toplayici_tanker_atama (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    firma_id INTEGER NOT NULL REFERENCES public.sirketler(id) ON DELETE CASCADE,
    -- Toplayıcının 'kullanicilar' tablosundaki ID'si
    toplayici_user_id BIGINT NOT NULL REFERENCES public.kullanicilar(id) ON DELETE CASCADE,
    tanker_id BIGINT NOT NULL REFERENCES public.tankerler(id) ON DELETE CASCADE,
    
    -- Bir toplayıcı aynı anda sadece bir tankere atanabilir
    CONSTRAINT toplayici_aktif_tanker_unique UNIQUE (toplayici_user_id)
);
-- İndeksler
CREATE INDEX idx_toplayici_tanker_atama_firma_id ON public.toplayici_tanker_atama(firma_id);
CREATE INDEX idx_toplayici_tanker_atama_user_id ON public.toplayici_tanker_atama(toplayici_user_id);
CREATE INDEX idx_toplayici_tanker_atama_tanker_id ON public.toplayici_tanker_atama(tanker_id);


-- 3. Süt girdileri tablosuna, hangi tankere eklendiğini bilmek için 'tanker_id' ekleme
ALTER TABLE public.sut_girdileri
ADD COLUMN tanker_id BIGINT REFERENCES public.tankerler(id) ON DELETE SET NULL; -- Tanker silinirse süt kaydı kalsın

CREATE INDEX IF NOT EXISTS idx_sut_girdileri_tanker_id
ON public.sut_girdileri(tanker_id);


-- 4. Süt Satışlarını (Tanker Boşaltma) kaydetmek için yeni tablo
CREATE TABLE public.sut_satis_islemleri (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firma_id INTEGER NOT NULL REFERENCES public.sirketler(id) ON DELETE CASCADE,
    kullanici_id BIGINT REFERENCES public.kullanicilar(id), -- Satışı yapan firma yöneticisi
    tanker_id BIGINT REFERENCES public.tankerler(id) ON DELETE SET NULL, -- Hangi tanker satıldı
    miktar_kg NUMERIC(10, 2) NOT NULL,
    birim_satis_fiyati NUMERIC(10, 2) NOT NULL,
    toplam_tutar NUMERIC(10, 2) NOT NULL,
    aciklama TEXT,
    islem_tarihi TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
-- İndeksler
CREATE INDEX idx_sut_satis_islemleri_firma_id ON public.sut_satis_islemleri(firma_id);
CREATE INDEX idx_sut_satis_islemleri_tanker_id ON public.sut_satis_islemleri(tanker_id);


-- 5. Finansal işlemlere, süt satışını bağlamak için 'sut_satis_id' ekleme
ALTER TABLE public.finansal_islemler
ADD COLUMN sut_satis_id BIGINT REFERENCES public.sut_satis_islemleri(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_finansal_islemler_sut_satis_id
ON public.finansal_islemler(sut_satis_id);


-- 6. Süt satışı yapıldığında Finans'a GELİR kaydı atan trigger fonksiyonu
CREATE OR REPLACE FUNCTION public.handle_sut_satisi_to_finans()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  finans_aciklama TEXT;
  tanker_adi TEXT;
BEGIN
  -- İlgili tankerin adını al
  SELECT t.tanker_adi INTO tanker_adi FROM public.tankerler t WHERE t.id = NEW.tanker_id;
  
  IF tanker_adi IS NULL THEN
    tanker_adi := 'Bilinmeyen Tanker';
  END IF;

  finans_aciklama := tanker_adi || ' Süt Satışı';
  
  IF NEW.aciklama IS NOT NULL AND NEW.aciklama != '' THEN
    finans_aciklama := finans_aciklama || ' (' || NEW.aciklama || ')';
  END IF;

  -- Finansal işlemlere GELİR olarak ekle
  INSERT INTO public.finansal_islemler
    (sirket_id, kullanici_id, islem_tipi, tutar, aciklama, sut_satis_id)
  VALUES
    (NEW.firma_id, NEW.kullanici_id, 'Süt Satışı', NEW.toplam_tutar, finans_aciklama, NEW.id);

  RETURN NEW;
END;
$$;

-- Trigger'ı oluştur
CREATE TRIGGER on_sut_satisi_created
  AFTER INSERT ON public.sut_satis_islemleri
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_sut_satisi_to_finans();


-- 7. Kârlılık Raporu'nu (get_karlilik_raporu) Süt Gelirini de içerecek şekilde GÜNCELLEME
DROP FUNCTION IF EXISTS public.get_karlilik_raporu(integer, text, text);

CREATE OR REPLACE FUNCTION public.get_karlilik_raporu (
  p_sirket_id integer,
  p_start_date text,
  p_end_date text
)
RETURNS json
LANGUAGE plpgsql
AS $$
DECLARE
    v_start_date date;
    v_end_date date;
    
    toplam_sut_maliyeti numeric;
    toplam_sut_geliri numeric; -- ARTIK HESAPLANACAK
    
    toplam_yem_maliyeti numeric;
    toplam_yem_geliri numeric;
    
    toplam_masraf numeric;
    toplam_diger_gelirler numeric;
    toplam_prim numeric;
BEGIN
    v_start_date := p_start_date::date;
    v_end_date := p_end_date::date;

    -- 1. Süt Maliyeti (GİDER - 'Süt Alımı')
    SELECT COALESCE(SUM(tutar), 0)
    INTO toplam_sut_maliyeti
    FROM public.finansal_islemler
    WHERE sirket_id = p_sirket_id
      AND islem_tipi = 'Süt Alımı'
      AND islem_tarihi BETWEEN v_start_date AND (v_end_date + interval '1 day');

    -- 2. Süt Geliri (GELİR - 'Süt Satışı' - YENİ EKLENDİ)
    SELECT COALESCE(SUM(tutar), 0)
    INTO toplam_sut_geliri
    FROM public.finansal_islemler
    WHERE sirket_id = p_sirket_id
      AND islem_tipi = 'Süt Satışı'
      AND islem_tarihi BETWEEN v_start_date AND (v_end_date + interval '1 day');

    -- 3. Yem Geliri (GELİR - 'Yem Satışı')
    SELECT COALESCE(SUM(tutar), 0)
    INTO toplam_yem_geliri
    FROM public.finansal_islemler
    WHERE sirket_id = p_sirket_id
      AND islem_tipi = 'Yem Satışı'
      AND islem_tarihi BETWEEN v_start_date AND (v_end_date + interval '1 day');

    -- 4. Yem Maliyeti (GİDER - 'Yem Alımı')
    SELECT COALESCE(SUM(tutar), 0)
    INTO toplam_yem_maliyeti
    FROM public.finansal_islemler
    WHERE sirket_id = p_sirket_id
      AND islem_tipi = 'Yem Alımı'
      AND islem_tarihi BETWEEN v_start_date AND (v_end_date + interval '1 day');

    -- 5. Diğer Giderler (Masraf, Prim, Diğer Gider)
    SELECT COALESCE(SUM(tutar), 0)
    INTO toplam_masraf
    FROM public.finansal_islemler
    WHERE sirket_id = p_sirket_id
      AND (islem_tipi = 'Masraf' OR islem_tipi = 'Diğer Gider')
      AND islem_tarihi BETWEEN v_start_date AND (v_end_date + interval '1 day');
      
    SELECT COALESCE(SUM(tutar), 0)
    INTO toplam_prim
    FROM public.finansal_islemler
    WHERE sirket_id = p_sirket_id
      AND islem_tipi = 'Prim'
      AND islem_tarihi BETWEEN v_start_date AND (v_end_date + interval '1 day');

    -- 6. Diğer Gelirler ('Diğer Gelir')
    SELECT COALESCE(SUM(tutar), 0)
    INTO toplam_diger_gelirler
    FROM public.finansal_islemler
    WHERE sirket_id = p_sirket_id
      AND islem_tipi = 'Diğer Gelir'
      AND islem_tarihi BETWEEN v_start_date AND (v_end_date + interval '1 day');

    -- Sonuçları JSON olarak döndür
    RETURN json_build_object(
        'sut_geliri', toplam_sut_geliri,
        'sut_maliyeti', toplam_sut_maliyeti,
        'sut_kari', (toplam_sut_geliri - toplam_sut_maliyeti),
        
        'yem_geliri', toplam_yem_geliri,
        'yem_maliyeti', toplam_yem_maliyeti, 
        'yem_kari', (toplam_yem_geliri - toplam_yem_maliyeti),
        
        'diger_gelirler', toplam_diger_gelirler,
        'diger_giderler', (toplam_masraf + toplam_prim),
        
        'toplam_gelir', (toplam_sut_geliri + toplam_yem_geliri + toplam_diger_gelirler),
        'toplam_gider', (toplam_sut_maliyeti + toplam_yem_maliyeti + toplam_masraf + toplam_prim),
        
        'net_kar', (
            (toplam_sut_geliri - toplam_sut_maliyeti) +
            (toplam_yem_geliri - toplam_yem_maliyeti) +
            toplam_diger_gelirler -
            (toplam_masraf + toplam_prim)
        )
    );
END;
$$;